### ISSUE TITLE
Update from svgo v1 to v2.3.0

### ISSUE THREAD

**Issue by JohnAlbin** [ben-eb/gulp-svgmin#108]
The version of svgo used in the package.json's dependencies is out-of-date.

**Comment by rejas** [comment]
Can't speak for @ben-eb but I dont have the time to make that bump since it seems they have changed quite some stuff in svgo v2. Unfortunately I couldnt find a migration guide neither. 
Or can you provide a PR doing the upgrade?

**Comment by ben-eb** [comment]
I'd happily accept a pull request for this, likewise I am short on time. :+1:
