### ISSUE TITLE
transformsWithOnePath plugin

### ISSUE THREAD

**Issue by dawidvdh** [ben-eb/gulp-svgmin#23]
Hi,

the transformsWithOnePath plugin, produces the following error ``` [TypeError: Cannot read property 'value' of undefined] ```

this is what my task currently looks like:

``` javascript
gulp.src([cfg.paths.assets+"webfont/*.svg"])
            .pipe(svgmin({
                plugins: [{
                    transformsWithOnePath: true
                }]
            }))
            .pipe(gulp.dest(cfg.paths.dest+'fonts/icons/'));
```

Any Help would be Greatly Appreciated.

**Comment by ben-eb** [comment]
Do you have a full stack trace?

**Comment by ben-eb** [comment]
Closing as stale.

**Comment by breeswish** [comment]
@ben-eb It is because `transformsWithOnePath` relies on `width` / `height` attribute, which might not exist because of the `removeDimensions` optimization. I cannot find a way to easily add back `width` / `height`. Could you re-open this issue?

**Comment by ben-eb** [comment]
@breeswish The svgo tracker is probably a better place for this issue.

**Comment by breeswish** [comment]
Thanks, you are right. I wasn't noticed that this is `gulp-svgmin` :P
