### ISSUE TITLE
How do you use plugins?

### ISSUE THREAD

**Issue by Jakobud** [ben-eb/gulp-svgmin#25]
For example I want to change the floatPrecision using the cleanupNumericValues plugin. I tried this:

    .pipe(svgmin({
	    cleanupNumericValues: {
		    floatPrecision: 1
    	    }
    }))

Didn't seem to work... What am I missing here? Do I need to load the plugin itself somehow?

**Comment by ben-eb** [comment]
Ensure that you are using the latest version, then:

```js
gulp.task('default', function() {
    return gulp.src('logo.svg')
        .pipe(svgmin({
            plugins: [{
                cleanupNumericValues: {
                    floatPrecision: 1
                }
            }]
        }))
        .pipe(gulp.dest('./out'));
});
```

**Comment by Jakobud** [comment]
Thanks. You should put that in the readme.

On a side note, are all plugins loaded by default? Is that how SVGO works?

**Comment by ben-eb** [comment]
I did. It's under 'plugins'. :smiley:

Not all plugins are loaded by default, e.g transformsWithOnePath. https://github.com/svg/svgo/blob/master/plugins/transformsWithOnePath.js

**Comment by Jakobud** [comment]
Ah okay I see now. That looked like only instructions on how to disable plugins. I didn't realize I could use the same syntax to pass options to plugins.

**Comment by ben-eb** [comment]
I'll look at revisiting the language for that section. :smile:
