### ISSUE TITLE
New Plugin

### ISSUE THREAD

**Issue by jolution** [ben-eb/gulp-svgmin#29]
Dear Developers,
ill like that gulp Plugin and write my first plugin, and if you like it, i can try to push it to github.
But my problem is that i cannot bring it to my gulp.

Ill override the "addClassesToSVGElement" file and than it works, but wanne have my own file.
I am very new to this. Ill read the manual here:
https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md
but it doesnt work, do you have any glue ?

Thanks very much!
Sorry for my bad english.

**Comment by ben-eb** [comment]
Hi @jolution,

Did you mean you added a plugin to perform SVG optimisation? If so it's probably best to discuss it in the [SVGO issue tracker](https://github.com/svg/svgo/issues).

To use a separate file you would need to modify https://github.com/svg/svgo/blob/master/.svgo.yml to use your plugin by default.

**Comment by jolution** [comment]
Hi @ben-eb,

Thanks for your fast Feedback.

Yes i (try to) add a plugin to perform SVG optimisation and add the new name to the yml file, but nothing happend.

Ok, if its the best, ill ask in the issue tracker by svgo.

Thanks,
Best,
Julian
