### ISSUE TITLE
Clarify default settings and which plugins are [ON].

### ISSUE THREAD

**Issue by hugolpz** [ben-eb/gulp-svgmin#31]
As I do the recommended : 

```
gulp.task('default', function () {
    return gulp.src('logo.svg')
        .pipe(svgmin())
        .pipe(gulp.dest('./out'));
});
```
I get an heavily lightened svg (great!!) without knowing which of [#of the SVGO plugins were ON and working](https://github.com/svg/svgo#what-it-can-do). As a first-time users, I want to know what is on/off at normal usage. The current tutorial (README.md) would gain to explain or link to the default settings relative to these plugins.

**Comment by ben-eb** [comment]
This is better documented upstream; svgo has a lot of dependents. Would be happy to include a link in this project's readme.

https://github.com/svg/svgo/issues/472
