### ISSUE TITLE
ViewBox will be removed regardless disabled plugin

### ISSUE THREAD

**Issue by bm2u** [ben-eb/gulp-svgmin#42]
As already mentioned in [svgo](https://github.com/svg/svgo/issues/505) gulp-svgmin does not respect the disabled "removeViewBox"-Plugin. My config looks like:

```
options : {
    plugins: [
        {
            removeViewBox: false
        },{
            addClassesToSVGElement: {
                classNames: ['svgo']
            }
        }
    ],
    js2svg: {
        pretty: true
    }
}
```
The class has been added to the svg element, but the viewbox unfortunately removed. Any ideas?

**Comment by ben-eb** [comment]
The options are passed directly to SVGO, we don't do anything special here. Perhaps it has some trouble with your particular SVG input?

**Comment by bm2u** [comment]
@ben-eb thx,known issue @svgo.

**Comment by ben-eb** [comment]
Closing this in favour of https://github.com/svg/svgo/issues/505
