### ISSUE TITLE
svgo 1.x: Promise based API

### ISSUE THREAD

**Issue by strarsis** [ben-eb/gulp-svgmin#75]
@ben-eb: svgo 1.0.0 and 1.0.1 have just been released which use a promise based API.

This postcss plugin should be updated to compatible with it, see
https://github.com/ben-eb/postcss-svgo/blob/master/src/index.js#L42 .

Example for using the new Promise based API, see
https://github.com/imagemin/imagemin-svgo/pull/27/files#diff-168726dbe96b3ce427e7fedce31bb0bcR18 .

**Comment by KingScooty** [comment]
@ben-eb Any news on this?

**Comment by rejas** [comment]
Fixed via https://github.com/ben-eb/gulp-svgmin/pull/86
