### ISSUE TITLE
Need deps updated to get latest plugins

### ISSUE THREAD

**Issue by rathpc** [ben-eb/gulp-svgmin#76]
Any chance you would be able to update the svgo dependency to be able to pull in the latest plugins released, specifically `inlineStyles`

**Comment by rathpc** [comment]
Checking back in on this. thank you! @ben-eb

**Comment by fictionic** [comment]
Also would like this. @ben-eb are you still alive????

**Comment by rathpc** [comment]
@fictionic I ended up using the gulp-imagemin plugin with the updated svgo plugin through there. Might be worth trying if no updates happen here.

**Comment by rejas** [comment]
Fixed via https://github.com/ben-eb/gulp-svgmin/pull/86
