### ISSUE TITLE
Upgrade SVGO to version 1.0.5?

### ISSUE THREAD

**Issue by KingScooty** [ben-eb/gulp-svgmin#81]
Just noticed this plugin is using SVGO 0.7.2. Can we upgrade to 1.0.5?

**Comment by nicolashenry** [comment]
I use ```gulp-svgo``` which seems to use the latest svgo if it helps.

**Comment by rejas** [comment]
Fixed via https://github.com/ben-eb/gulp-svgmin/pull/86
