### ISSUE TITLE
convert ids to class names

### ISSUE THREAD

**Issue by v3nt** [ben-eb/gulp-svgmin#84]
Hello - great little set of scripts! Is there a way to convert any ids to classes or perhaps data-id ?

thanks, D.

**Comment by ben-eb** [comment]
Hey @v3nt, please could you report this to https://github.com/svg/svgo if you are still having this issue? This plugin is a thin wrapper on top of svgo to use it with gulp, and so this is better reported upstream. Thanks. 👍
