### ISSUE TITLE
Maintaining the project?

### ISSUE THREAD

**Issue by rejas** [ben-eb/gulp-svgmin#85]
Hi @ben-eb 
since there are some PR hanging in a limbo with you seemingly not maintaining the plugin, would you be interested in handing over maintainership to somebody else or maybe to https://github.com/gulp-community/ ? 
If you just want some help without giving up maintainership, I am happy to offer my assistance.
Cceers

**Comment by ben-eb** [comment]
@rejas It's done. 👍

**Comment by rejas** [comment]
Thx @ben-eb, already cleaned up some stuff :-)
