### ISSUE TITLE
NaNs in path

### ISSUE THREAD

**Issue by Egor812** [ben-eb/gulp-svgmin#99]
Wrong conversion of Fontawesome icon:
`<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="phone-square" class="svg-inline--fa fa-phone-square fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M400 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zM94 416c-7.033 0-13.057-4.873-14.616-11.627l-14.998-65a15 15 0 0 1 8.707-17.16l69.998-29.999a15 15 0 0 1 17.518 4.289l30.997 37.885c48.944-22.963 88.297-62.858 110.781-110.78l-37.886-30.997a15.001 15.001 0 0 1-4.289-17.518l30-69.998a15 15 0 0 1 17.16-8.707l65 14.998A14.997 14.997 0 0 1 384 126c0 160.292-129.945 290-290 290z"></path></svg>`
converts to
`<symbol id="icon-phone-square-solid" viewBox="0 0 448 512">
	<path d="M400 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zM94 416c-7.033 0-13.057-4.873-14.616-11.627l-14.998-65a15 15 0 18.707-17.16 NaN NaNlNaN NaNa15 15 0 117.518 4.289 NaN NaNlNaN NaNcNaN NaN NaN NaN NaN NaNlNaN NaNa15.001 15.001 0 1-4.289 NaN NaNlNaN NaNa15 15 0 117.16-8.707 NaN NaNlNaN NaNa14.997 14.997 0 1384 126 NaN NaNcNaN NaN NaN NaN NaN NaNz"></path>
</symbol>`

**Comment by rejas** [comment]
could you please provide which version of gulp-svgmin you are using?

**Comment by s-pyadyshev** [comment]
I have the same issue with "gulp-svgmin": "^1.2.4",

**Comment by rejas** [comment]
HI @s-pyadyshev  and @Egor812 could you chck if using the branch "cleanups" https://github.com/ben-eb/gulp-svgmin/tree/cleanup fixes your problems?

**Comment by ben-eb** [comment]
Hey @Egor812 , please could you report this to https://github.com/svg/svgo if you are still having this issue? This plugin is a thin wrapper on top of svgo to use it with gulp, and so this is better reported upstream. Thanks. 👍
